# Generated by Django 4.2.1 on 2023-06-01 12:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spoor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 12, 4, 10, 691241)),
        ),
        migrations.AddField(
            model_name='credential',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
