# Generated by Django 4.2.1 on 2023-06-03 00:06

import datetime
from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spoor', '0002_credential_created_at_credential_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='encrypted_refresh',
            field=django_cryptography.fields.encrypt(models.TextField(default='a')),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 0, 5, 41, 317055)),
        ),
    ]
