# Generated by Django 4.2.3 on 2023-07-13 00:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('spoor', '0003_credential_encrypted_refresh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('26438def-7579-49ee-a531-1a2e811961f7'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=255)),
                ('retrieval_id', models.CharField(max_length=255, unique=True)),
                ('redirect_url', models.URLField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='last_track_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='credential',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 0, 16, 16, 964087)),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('371e2a24-0378-4d1f-8217-efe2b3145cb0'), editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SP', 'Spotify')], default='SP', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('retrieval_id', models.CharField(max_length=255, unique=True)),
                ('retrieval_url', models.URLField(unique=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 7, 13, 0, 16, 16, 965565))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spoor.profile')),
            ],
        ),
    ]
